name: Auto deployment

on:
  push:
    branches: main
    paths-ignore:
      - '.eslintrc'
      - '.prettierrc'
      - 'README.md'
      - 'License'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          proxy_host: ${{ secrets.BASTION_HOST_IP }}
          proxy_username: ${{ secrets.BASTION_HOST_USERNAME }}
          proxy_key: ${{ secrets.BASTION_HOST_KEY }}
          host: ${{ secrets.APP_SERVER_IP }}
          username: ${{ secrets.APP_SERVER_USERNAME }}
          key: ${{ secrets.APP_SERVER_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.APP_PATH }}
            git pull
            npm install
            npm run build
            pm2 restart server
